language: ruby

sudo: false
cache:
  - bundler

env:
  - COVERALL=1

notifications:
  email:
    - weppos@weppos.net

matrix:
  include:
    - rvm: 2.0
      gemfile: Gemfile.activesupport-4.x
    - rvm: 2.1
      gemfile: Gemfile.activesupport-4.x
    - rvm: 2.2
      gemfile: Gemfile.activesupport-4.x
    - rvm: jruby-9.0.5.0
      gemfile: Gemfile
    - rvm: jruby-9.0.5.0
      gemfile: Gemfile.activesupport-4.x
    - rvm: ruby-head
      gemfile: Gemfile.activesupport-4.x
    - rvm: ruby-head
      gemfile: Gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.5.0
