language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - jruby-9.0.5.0
  - ruby-head
gemfile:
  - Gemfile
  - Gemfile.activesupport-4.x

sudo: false
cache:
  - bundler

env:
  - COVERALL=1

notifications:
  recipients:
    - weppos@weppos.net

matrix:
  exclude:
    - rvm: 2.0
      gemfile: Gemfile
    - rvm: 2.1
      gemfile: Gemfile
    - rvm: 2.2
      gemfile: Gemfile
    - rvm: jruby-9.0.5.0
      env: COVERALL=1
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.5.0
